### ISSUE TITLE
Group name doesn't show for Uploads in search results

### ISSUE THREAD

**Issue by shirey** [hubmapconsortium/ingest-ui#1058] opened 2023-03-06 19:41 UTC
![image](https://user-images.githubusercontent.com/5816400/223214660-f8c6fed4-4281-4755-bb5a-be7f9cb31201.png)

**Comment by BirdMachine** [comment] 2023-04-05 13:35
Dupe of #955 and dependent on Search API's https://github.com/hubmapconsortium/search-api/issues/451

**Closed by BirdMachine** 2023-04-05 13:35 UTC
Labels: P
