### ISSUE TITLE
Dataset data type selection and save bugs on Edit screen

### ISSUE THREAD

**Issue by yuanzhou** [hubmapconsortium/ingest-ui#801] opened 2022-02-07 17:49 UTC
On TEST, dataset 488f364142c308a9692e0b529f6697dd has the data type snRNAseq-10xGenomics-v2 but the ingest-ui is not displaying it as the selected data type on edit screen. And when we tried to re-select the correct value from the dropdown, got an error:

![image](https://user-images.githubusercontent.com/195873/152843430-a92c968c-9897-4c35-837e-41a902969484.png)
![image](https://user-images.githubusercontent.com/195873/152843462-be069e0c-3663-4393-abda-f50d09621188.png)

The data type stored in neo4j:
![image](https://user-images.githubusercontent.com/195873/152843602-a0c91f1a-acb5-4a30-8b86-79c34819acb7.png)

**Comment by yuanzhou** [comment] 2022-02-08 02:40
From Bill:
>there was an extra space at the end of the assay code, I fixed in the DB

**Comment by shirey** [comment] 2022-02-08 02:50
This was caused by me manually editing the data to get around several other bugs, once these other bugs are fixed this issue won't be needed.

**Comment by BirdMachine** [comment] 2023-01-24 20:03
Addressed in pr #864

**Closed by BirdMachine** 2023-01-24 20:03 UTC
Labels: triage
