### ISSUE TITLE
[Bug report] Sample bulk registration yielded gray screen with no report table

### ISSUE THREAD

**Issue by bhonick** [hubmapconsortium/ingest-ui#1250] opened 2023-10-12 14:21 UTC
Hi @shirey @BirdMachine , a data provider from TMC-UCSD Repro reported the following issue when attempting to bulk register some tissue blocks from organs: "I just did a bulk registration of 76 samples and it appeared to work up until the last step where the whole screen went gray. I looked up one of the samples (using our lab id) and was able to find it, so I think the samples were ingested, there was just a glitch and I didn’t get the final screen that shows a table with the new HuBMAP IDs." 

I've checked, and these blocks were indeed registered despite the issue with the final screen. The table used for bulk registration can be found here: https://drive.google.com/file/d/1JBqHLKkaR16BnBByrEIiufBwlUCbYqSZ/view?usp=sharing. I'd appreciate it if you could take a look at this. Thanks!

**Comment by yuanzhou** [comment] 2023-10-27 20:31
@bhonick we were able to reproduce this issue on DEV. It was due to a server timeout issue since the registration could take over 5 minutes with the provided TSV. You are correct, the backend process did go through and all the samples were registered. Although a proper response didn't come back before the proxy server timeout.

From your perspective, would it be a good idea if the UI displays a message and ask the user to come back after a few more minutes while the backend is still processing?

**Comment by bhonick** [comment] 2023-10-31 19:19
Hi @yuanzhou, yes, I think that would be a suitable approach.

**Comment by yuanzhou** [comment] 2023-10-31 20:26
@bhonick in addition to the increased timeout settings, @BirdMachine also added instructional message as well as validations to prevent the TSV with more than 40 rows. This will be released this week.

**Comment by bhonick** [comment] 2023-10-31 20:32
@yuanzhou @BirdMachine For clarity, why the 40 row limit?

**Comment by yuanzhou** [comment] 2023-11-01 13:54
@bhonick we understand from the data provider's perspective. 40 is not a silver bullet, but >=50 could cause the same timeout from our observation. Just to be on the safe side, if the data providers will need to more than 40 rows, they'll have to split the the data into multiple TSV files and submit individually. The end result will be the same.

The ingest-api is the only API that runs on PSC and doesn't go through AWS API Gateway, which makes it possible for us to use a much bigger timeout. Otherwise, 29 seconds is the hard limit and we won't be able to accommodate even close to 40 rows.

**Comment by bhonick** [comment] 2023-11-01 15:07
@yuanzhou Thanks for the clarification! That makes sense to me, and I'll keep that in mind as I work with data providers.

**Closed** 2023-12-14 18:09 UTC
Labels: bug, fire drill, P
